{{- if or .Values.hiveserver2.enabled .Values.metastore.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}-hive-site
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  hive-site.xml: |
    {{- include "hive.hiveSiteXml" (dict "default" .Values.hiveSite.properties "override" .Values.hiveserver2.hiveSite.properties) | nindent 4 }}
{{- end -}}
