{{- if and .Values.metastore.enabled .Values.metastore.database.enabled -}}
apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: '{{ .Release.Name }}-hms-db'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "hive.labels" . | nindent 4 }}
    app.kubernetes.io/component: metastore
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.metastore.database.backup }}
  backup:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  engine:
    replicas: {{ .Values.metastore.database.engine.replicas }}
    resources:
      cpu: '{{ .Values.metastore.database.engine.resources.cpu }}'
      memory: {{ .Values.metastore.database.engine.resources.memory }}
    storage:
      class: {{ .Values.metastore.database.engine.storage.class }}
      size: {{ .Values.metastore.database.engine.storage.size }}
    type: {{ .Values.metastore.database.engine.type }}
    version: '{{ .Values.metastore.database.engine.version }}'
  {{- with .Values.metastore.database.monitoring }}
  monitoring:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metastore.database.proxy }}
  proxy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
