{{- if .Values.metastore.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hive.fullname" . }}-metastore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
    app.kubernetes.io/component: metastore
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.metastore.replicas | default .Values.replicas }}
  selector:
    matchLabels:
      {{- include "hive.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metastore
  template:
    metadata:
      labels:
        {{- include "hive.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: metastore
    spec:
      {{- if (.Values.metastore.imagePullSecrets | default .Values.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml (.Values.metastore.imagePullSecrets | default .Values.imagePullSecrets) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hive.serviceAccountName" . }}
      volumes:
        - name: hive-site-config
          configMap:
            name: {{ include "hive.fullname" . }}-hive-site
        - name: metastore-site-config
          configMap:
            name: {{ include "hive.fullname" . }}-metastore-site
        - name: credential-provider-volume
          emptyDir: {}
        {{- if .Values.metastore.extraVolumes }}
        {{- toYaml .Values.metastore.extraVolumes | nindent 8 }}
        {{- end }}
      {{- if or .Values.metastore.initContainers .Values.metastore.database.enabled }}
      initContainers:
        {{- if and .Values.metastore.database.enabled (eq .Values.metastore.database.engine.type "postgresql") }}
        - name: 01-wait-for-db
          image: postgres:alpine
          env:
            - name: HMS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'pgbouncer-host'
            - name: HMS_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'pgbouncer-port'
            - name: HMS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'user'
            - name: HMS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'password'
          command: ["/bin/sh", "-c"]
          args:
            - |
              export PGPASSWORD="$HMS_DB_PASSWORD"
              until pg_isready -h "$HMS_DB_HOST" -p "$HMS_DB_PORT" -U "$HMS_DB_USER"; do
                echo "Waiting for PgBouncer..."
                sleep 5
              done
              echo "PgBouncer is reachable."
              until psql -h "$HMS_DB_HOST" -p "$HMS_DB_PORT" -U "$HMS_DB_USER" -d postgres -c "SELECT 1;" >/dev/null 2>&1; do
                echo "Waiting for PostgreSQL backend..."
                sleep 5
              done
              echo "Backend PostgreSQL is reachable through PgBouncer."
        - name: 02-init-db
          image: postgres:alpine
          env:
            - name: HMS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'pgbouncer-host'
            - name: HMS_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'pgbouncer-port'
            - name: HMS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'user'
            - name: HMS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'password'
          command: ["/bin/sh", "-c"]
          args:
            - |
              export PGPASSWORD=$HMS_DB_PASSWORD
              if ! psql -h $HMS_DB_HOST -p $HMS_DB_PORT -U $HMS_DB_USER -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='metastore'" | grep -q 1; then
                psql -h $HMS_DB_HOST -p $HMS_DB_PORT -U $HMS_DB_USER -d postgres -c "CREATE DATABASE metastore;"
                echo "Database 'metastore' created."
              else
                echo "Database 'metastore' already exists."
              fi
        - name: 03-setup-credential-provider
          image: {{ include "hive.componentImage" (dict "global" .Values.image "component" .Values.metastore.image "chart" .Chart) }}
          env:
            - name: HMS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'password'
          volumeMounts:
            - name: credential-provider-volume
              mountPath: /opt/hive/secrets
          command: ["/bin/sh", "-c"]
          args:
            - |
              hadoop credential create javax.jdo.option.ConnectionPassword \
                -value ${HMS_DB_PASSWORD} \
                -provider jceks://file/opt/hive/secrets/hive.jceks
        {{- end }}
        {{- if .Values.metastore.initContainers }}
        {{- tpl (toYaml .Values.metastore.initContainers) . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: metastore
          image: {{ include "hive.componentImage" (dict "global" .Values.image "component" .Values.metastore.image "chart" .Chart) }}
          imagePullPolicy: {{ .Values.metastore.image.pullPolicy | default .Values.image.pullPolicy }}
          env:
            - name: SERVICE_NAME
              value: metastore
            {{- if and .Values.metastore.database.enabled (eq .Values.metastore.database.engine.type "postgresql") }}
            - name: DB_DRIVER
              value: "postgres"
            - name: HMS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'pgbouncer-host'
            - name: HMS_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'pgbouncer-port'
            - name: HMS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: 'everest-secrets-{{ .Release.Name }}-hms-db'
                  key: 'user'
            - name: SERVICE_OPTS
              value: >
                -Xmx2G
                -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://$(HMS_DB_HOST):$(HMS_DB_PORT)/metastore
                -Djavax.jdo.option.ConnectionUserName=$(HMS_DB_USER)
            {{- end }}
            {{- $envYaml := include "hive.mergeEnv" (dict "defaultEnv" .Values.env "specificEnv" .Values.metastore.env) -}}
            {{- if $envYaml }}
            {{- $envYaml | nindent 12 }}
            {{- end }}
          {{- if .Values.metastore.envFrom }}
          envFrom:
            {{- toYaml .Values.metastore.envFrom | nindent 12 }}
          {{- end }}
          ports:
            - name: thrift
              containerPort: {{ .Values.metastore.service.port }}
              protocol: TCP
          volumeMounts:
            - name: hive-site-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: metastore-site-config
              mountPath: /opt/hive/conf/metastore-site.xml
              subPath: metastore-site.xml
            - name: credential-provider-volume
              mountPath: /opt/hive/secrets
            {{- if .Values.metastore.extraVolumeMounts }}
            {{- toYaml .Values.metastore.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- with .Values.metastore.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            tcpSocket:
              port: {{ .Values.metastore.service.port }}
            failureThreshold: {{ .Values.metastore.startupProbe.failureThreshold | default 30 }}
            periodSeconds: {{ .Values.metastore.startupProbe.periodSeconds | default 10 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.metastore.service.port }}
            initialDelaySeconds: {{ .Values.metastore.livenessProbe.initialDelaySeconds | default 15 }}
            periodSeconds: {{ .Values.metastore.livenessProbe.periodSeconds | default 20 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.metastore.service.port }}
            initialDelaySeconds: {{ .Values.metastore.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.metastore.readinessProbe.periodSeconds | default 10 }}
{{- end -}}
