{{- if .Values.metastore.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}-metastore-site
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hive.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  metastore-site.xml: |
    {{- include "hive.hiveSiteXml" (dict "default" (.Values.metastoreSite.properties | default dict) "override" (.Values.metastore.metastoreSite.properties | default dict)) | nindent 4 }}
{{- end -}}
