{{- if .Values.coordinatorIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trino.fullname" . }}-coordinator-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.coordinatorIngress.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.coordinatorIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.coordinatorIngress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.coordinatorIngress.host | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "trino.fullname" . }}
                port:
                  number: {{ .Values.coordinatorIngress.port }}
            path: /
            pathType: ImplementationSpecific
  {{- if .Values.coordinatorIngress.tls }}
  tls:
    {{- toYaml .Values.coordinatorIngress.tls | nindent 4 }}
  {{- end }}
{{- end }}
